completed_jobs:
- kdd99-unsupervised-ad
- http
- ForestCover
- mammography
- creditcard
failed_jobs: []
pending_datasets: []
submitted_jobs:
  ForestCover: '2660010'
  creditcard: '2660009'
  http: '2660011'
  kdd99-unsupervised-ad: '2660012'
  mammography: '2660008'
timestamp: '2025-12-23T14:35:39.338074'
