completed_jobs:
- creditcard
- http
- mulcross
- ForestCover
- kdd99-unsupervised-ad
failed_jobs: []
pending_datasets: []
submitted_jobs:
  ForestCover: '2595287'
  creditcard: '2571011'
  http: '2595836'
  kdd99-unsupervised-ad: '2571013'
  mulcross: '2571012'
timestamp: '2025-12-13T02:18:25.389739'
