completed_jobs: []
failed_jobs: []
pending_datasets:
- pen-global-unsupervised-ad
- PenDigits_withoutdupl_norm_v01
- InternetAds_norm_02_v01
- mammography
- satellite-unsupervised-ad
- shuttle-unsupervised-ad
- creditcard
- kdd99-unsupervised-ad
submitted_jobs:
  annthyroid-unsupervised-ad: DRYRUN_annthyroid-unsupervised-ad
  breast-cancer-unsupervised-ad: DRYRUN_breast-cancer-unsupervised-ad
  dfki-artificial-3000-unsupervised-ad: DRYRUN_dfki-artificial-3000-unsupervised-ad
  pen-local-unsupervised-ad: DRYRUN_pen-local-unsupervised-ad
timestamp: '2025-12-08T16:22:22.730320'
